### ISSUE TITLE
当前项目进度

### ISSUE THREAD

**Issue by doraemonext** [doraemonext/wechat-platform#1]
- [x] [系统] 系统基本框架
- [x] [前端] 公众号设置
- [x] [系统] 公众号切换
- [x] [系统] 素材库文件集中为单一Model
- [x] [API] 音乐素材库
- [x] [前端] 音乐素材库
- [ ] [API] 语音素材库
- [ ] [前端] 语音素材库
- [ ] [API] 图片素材库
- [ ] [前端] 图片素材库
- [x] [API] 图文素材库
- [ ] [前端] 图文素材库
- [ ] [API] 规则管理
- [ ] [前端] 规则管理
- [ ] [API] 默认回复管理
- [ ] [前端] 默认回复管理
- [ ] [API] 订阅回复管理
- [ ] [前端] 订阅回复管理
- [ ] [API] 系统设置
- [ ] [前端] 系统设置
- [ ] [API] 插件设置
- [ ] [前端] 插件设置

**Comment by passioncsu** [comment]
up主怎么还不更新啊，等着用呢，而且有没有群之类的，想加进去讨论。回头帮忙写个doc啥的

**Comment by doraemonext** [comment]
这几天正在集中考试 T^T，基本没有写代码……

我的QQ：1422526，一起讨论 >_<

**Comment by perkfly** [comment]
up主加油

**Comment by doraemonext** [comment]
@yifeikong 谢谢

**Comment by gatspy** [comment]
这个项目还会更新吗？

**Comment by yarving** [comment]
这个项目还会更新吗？

**Comment by doraemonext** [comment]
@yarving 已经停止更新。
